/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardKeysRouteImport } from './routes/dashboard/keys'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiKeysRouteImport } from './routes/api/keys'
import { Route as ApiIngestUrlRouteImport } from './routes/api/ingest-url'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiEmbedRouteImport } from './routes/api/embed'
import { Route as ApiDeviceTokenRouteImport } from './routes/api/device-token'
import { Route as ApiCrawlRouteImport } from './routes/api/crawl'
import { Route as ApiContextRouteImport } from './routes/api/context'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardLibrariesIndexRouteImport } from './routes/dashboard/libraries/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as ApiLibrariesIndexRouteImport } from './routes/api/libraries/index'
import { Route as DashboardLibrariesAddRouteImport } from './routes/dashboard/libraries/add'
import { Route as DashboardLibrariesIdRouteImport } from './routes/dashboard/libraries/$id'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiLibrariesIdRouteImport } from './routes/api/libraries/$id'
import { Route as ApiCronRefreshRouteImport } from './routes/api/cron/refresh'
import { Route as ApiCronDiscoveryRouteImport } from './routes/api/cron/discovery'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminLibrariesRouteImport } from './routes/api/admin/libraries'
import { Route as DashboardAdminUsersIdRouteImport } from './routes/dashboard/admin/users/$id'
import { Route as ApiLibrariesIdRepoRouteImport } from './routes/api/libraries/$id/repo'
import { Route as ApiLibrariesIdDocsRouteImport } from './routes/api/libraries/$id/docs'
import { Route as ApiGithubVerifyCallbackRouteImport } from './routes/api/github/verify/callback'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiAdminDiscoverySourcesRouteImport } from './routes/api/admin/discovery/sources'
import { Route as ApiAdminDiscoveryRunRouteImport } from './routes/api/admin/discovery/run'
import { Route as ApiAdminDiscoveryQueueRouteImport } from './routes/api/admin/discovery/queue'
import { Route as ApiLibrariesIdRepoVerifyRouteImport } from './routes/api/libraries/$id/repo/verify'
import { Route as ApiLibrariesIdRepoIngestRouteImport } from './routes/api/libraries/$id/repo/ingest'
import { Route as ApiLibrariesIdDocsBuildRouteImport } from './routes/api/libraries/$id/docs/build'
import { Route as ApiAdminUsersIdFlagsRouteImport } from './routes/api/admin/users/$id/flags'
import { Route as ApiAdminLibrariesIdRebuildRouteImport } from './routes/api/admin/libraries/$id/rebuild'
import { Route as ApiAdminLibrariesIdCategoryRouteImport } from './routes/api/admin/libraries/$id/category'
import { Route as ApiAdminDiscoverySourcesIdRouteImport } from './routes/api/admin/discovery/sources/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestUrlRoute = ApiIngestUrlRouteImport.update({
  id: '/api/ingest-url',
  path: '/api/ingest-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedRoute = ApiEmbedRouteImport.update({
  id: '/api/embed',
  path: '/api/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceTokenRoute = ApiDeviceTokenRouteImport.update({
  id: '/api/device-token',
  path: '/api/device-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlRoute = ApiCrawlRouteImport.update({
  id: '/api/crawl',
  path: '/api/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextRoute = ApiContextRouteImport.update({
  id: '/api/context',
  path: '/api/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLibrariesIndexRoute = DashboardLibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiLibrariesIndexRoute = ApiLibrariesIndexRouteImport.update({
  id: '/api/libraries/',
  path: '/api/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLibrariesAddRoute = DashboardLibrariesAddRouteImport.update({
  id: '/libraries/add',
  path: '/libraries/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibrariesIdRoute = DashboardLibrariesIdRouteImport.update({
  id: '/libraries/$id',
  path: '/libraries/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibrariesIdRoute = ApiLibrariesIdRouteImport.update({
  id: '/api/libraries/$id',
  path: '/api/libraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshRoute = ApiCronRefreshRouteImport.update({
  id: '/api/cron/refresh',
  path: '/api/cron/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDiscoveryRoute = ApiCronDiscoveryRouteImport.update({
  id: '/api/cron/discovery',
  path: '/api/cron/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLibrariesRoute = ApiAdminLibrariesRouteImport.update({
  id: '/api/admin/libraries',
  path: '/api/admin/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminUsersIdRoute = DashboardAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiLibrariesIdRepoRoute = ApiLibrariesIdRepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => ApiLibrariesIdRoute,
} as any)
const ApiLibrariesIdDocsRoute = ApiLibrariesIdDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ApiLibrariesIdRoute,
} as any)
const ApiGithubVerifyCallbackRoute = ApiGithubVerifyCallbackRouteImport.update({
  id: '/api/github/verify/callback',
  path: '/api/github/verify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminDiscoverySourcesRoute =
  ApiAdminDiscoverySourcesRouteImport.update({
    id: '/api/admin/discovery/sources',
    path: '/api/admin/discovery/sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDiscoveryRunRoute = ApiAdminDiscoveryRunRouteImport.update({
  id: '/api/admin/discovery/run',
  path: '/api/admin/discovery/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDiscoveryQueueRoute = ApiAdminDiscoveryQueueRouteImport.update({
  id: '/api/admin/discovery/queue',
  path: '/api/admin/discovery/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibrariesIdRepoVerifyRoute =
  ApiLibrariesIdRepoVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiLibrariesIdRepoRoute,
  } as any)
const ApiLibrariesIdRepoIngestRoute =
  ApiLibrariesIdRepoIngestRouteImport.update({
    id: '/ingest',
    path: '/ingest',
    getParentRoute: () => ApiLibrariesIdRepoRoute,
  } as any)
const ApiLibrariesIdDocsBuildRoute = ApiLibrariesIdDocsBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => ApiLibrariesIdDocsRoute,
} as any)
const ApiAdminUsersIdFlagsRoute = ApiAdminUsersIdFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiAdminLibrariesIdRebuildRoute =
  ApiAdminLibrariesIdRebuildRouteImport.update({
    id: '/$id/rebuild',
    path: '/$id/rebuild',
    getParentRoute: () => ApiAdminLibrariesRoute,
  } as any)
const ApiAdminLibrariesIdCategoryRoute =
  ApiAdminLibrariesIdCategoryRouteImport.update({
    id: '/$id/category',
    path: '/$id/category',
    getParentRoute: () => ApiAdminLibrariesRoute,
  } as any)
const ApiAdminDiscoverySourcesIdRoute =
  ApiAdminDiscoverySourcesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminDiscoverySourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/context': typeof ApiContextRoute
  '/api/crawl': typeof ApiCrawlRoute
  '/api/device-token': typeof ApiDeviceTokenRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/ingest-url': typeof ApiIngestUrlRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/libraries': typeof ApiAdminLibrariesRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/discovery': typeof ApiCronDiscoveryRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/libraries/$id': typeof ApiLibrariesIdRouteWithChildren
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/dashboard/libraries/$id': typeof DashboardLibrariesIdRoute
  '/dashboard/libraries/add': typeof DashboardLibrariesAddRoute
  '/api/libraries/': typeof ApiLibrariesIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/libraries/': typeof DashboardLibrariesIndexRoute
  '/api/admin/discovery/queue': typeof ApiAdminDiscoveryQueueRoute
  '/api/admin/discovery/run': typeof ApiAdminDiscoveryRunRoute
  '/api/admin/discovery/sources': typeof ApiAdminDiscoverySourcesRouteWithChildren
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/github/verify/callback': typeof ApiGithubVerifyCallbackRoute
  '/api/libraries/$id/docs': typeof ApiLibrariesIdDocsRouteWithChildren
  '/api/libraries/$id/repo': typeof ApiLibrariesIdRepoRouteWithChildren
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/api/admin/discovery/sources/$id': typeof ApiAdminDiscoverySourcesIdRoute
  '/api/admin/libraries/$id/category': typeof ApiAdminLibrariesIdCategoryRoute
  '/api/admin/libraries/$id/rebuild': typeof ApiAdminLibrariesIdRebuildRoute
  '/api/admin/users/$id/flags': typeof ApiAdminUsersIdFlagsRoute
  '/api/libraries/$id/docs/build': typeof ApiLibrariesIdDocsBuildRoute
  '/api/libraries/$id/repo/ingest': typeof ApiLibrariesIdRepoIngestRoute
  '/api/libraries/$id/repo/verify': typeof ApiLibrariesIdRepoVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/device': typeof DeviceRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/context': typeof ApiContextRoute
  '/api/crawl': typeof ApiCrawlRoute
  '/api/device-token': typeof ApiDeviceTokenRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/ingest-url': typeof ApiIngestUrlRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/libraries': typeof ApiAdminLibrariesRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/discovery': typeof ApiCronDiscoveryRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/libraries/$id': typeof ApiLibrariesIdRouteWithChildren
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/dashboard/libraries/$id': typeof DashboardLibrariesIdRoute
  '/dashboard/libraries/add': typeof DashboardLibrariesAddRoute
  '/api/libraries': typeof ApiLibrariesIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/libraries': typeof DashboardLibrariesIndexRoute
  '/api/admin/discovery/queue': typeof ApiAdminDiscoveryQueueRoute
  '/api/admin/discovery/run': typeof ApiAdminDiscoveryRunRoute
  '/api/admin/discovery/sources': typeof ApiAdminDiscoverySourcesRouteWithChildren
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/github/verify/callback': typeof ApiGithubVerifyCallbackRoute
  '/api/libraries/$id/docs': typeof ApiLibrariesIdDocsRouteWithChildren
  '/api/libraries/$id/repo': typeof ApiLibrariesIdRepoRouteWithChildren
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/api/admin/discovery/sources/$id': typeof ApiAdminDiscoverySourcesIdRoute
  '/api/admin/libraries/$id/category': typeof ApiAdminLibrariesIdCategoryRoute
  '/api/admin/libraries/$id/rebuild': typeof ApiAdminLibrariesIdRebuildRoute
  '/api/admin/users/$id/flags': typeof ApiAdminUsersIdFlagsRoute
  '/api/libraries/$id/docs/build': typeof ApiLibrariesIdDocsBuildRoute
  '/api/libraries/$id/repo/ingest': typeof ApiLibrariesIdRepoIngestRoute
  '/api/libraries/$id/repo/verify': typeof ApiLibrariesIdRepoVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/context': typeof ApiContextRoute
  '/api/crawl': typeof ApiCrawlRoute
  '/api/device-token': typeof ApiDeviceTokenRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/ingest-url': typeof ApiIngestUrlRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/libraries': typeof ApiAdminLibrariesRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/discovery': typeof ApiCronDiscoveryRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/libraries/$id': typeof ApiLibrariesIdRouteWithChildren
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/dashboard/libraries/$id': typeof DashboardLibrariesIdRoute
  '/dashboard/libraries/add': typeof DashboardLibrariesAddRoute
  '/api/libraries/': typeof ApiLibrariesIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/libraries/': typeof DashboardLibrariesIndexRoute
  '/api/admin/discovery/queue': typeof ApiAdminDiscoveryQueueRoute
  '/api/admin/discovery/run': typeof ApiAdminDiscoveryRunRoute
  '/api/admin/discovery/sources': typeof ApiAdminDiscoverySourcesRouteWithChildren
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/github/verify/callback': typeof ApiGithubVerifyCallbackRoute
  '/api/libraries/$id/docs': typeof ApiLibrariesIdDocsRouteWithChildren
  '/api/libraries/$id/repo': typeof ApiLibrariesIdRepoRouteWithChildren
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/api/admin/discovery/sources/$id': typeof ApiAdminDiscoverySourcesIdRoute
  '/api/admin/libraries/$id/category': typeof ApiAdminLibrariesIdCategoryRoute
  '/api/admin/libraries/$id/rebuild': typeof ApiAdminLibrariesIdRebuildRoute
  '/api/admin/users/$id/flags': typeof ApiAdminUsersIdFlagsRoute
  '/api/libraries/$id/docs/build': typeof ApiLibrariesIdDocsBuildRoute
  '/api/libraries/$id/repo/ingest': typeof ApiLibrariesIdRepoIngestRoute
  '/api/libraries/$id/repo/verify': typeof ApiLibrariesIdRepoVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/device'
    | '/docs'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/chat'
    | '/api/context'
    | '/api/crawl'
    | '/api/device-token'
    | '/api/embed'
    | '/api/ingest'
    | '/api/ingest-url'
    | '/api/keys'
    | '/api/mcp'
    | '/api/search'
    | '/dashboard/chat'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/admin/libraries'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/cron/discovery'
    | '/api/cron/refresh'
    | '/api/libraries/$id'
    | '/api/webhooks/github'
    | '/dashboard/libraries/$id'
    | '/dashboard/libraries/add'
    | '/api/libraries/'
    | '/dashboard/admin/'
    | '/dashboard/libraries/'
    | '/api/admin/discovery/queue'
    | '/api/admin/discovery/run'
    | '/api/admin/discovery/sources'
    | '/api/admin/users/$id'
    | '/api/github/verify/callback'
    | '/api/libraries/$id/docs'
    | '/api/libraries/$id/repo'
    | '/dashboard/admin/users/$id'
    | '/api/admin/discovery/sources/$id'
    | '/api/admin/libraries/$id/category'
    | '/api/admin/libraries/$id/rebuild'
    | '/api/admin/users/$id/flags'
    | '/api/libraries/$id/docs/build'
    | '/api/libraries/$id/repo/ingest'
    | '/api/libraries/$id/repo/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/device'
    | '/docs'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/chat'
    | '/api/context'
    | '/api/crawl'
    | '/api/device-token'
    | '/api/embed'
    | '/api/ingest'
    | '/api/ingest-url'
    | '/api/keys'
    | '/api/mcp'
    | '/api/search'
    | '/dashboard/chat'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/admin/libraries'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/cron/discovery'
    | '/api/cron/refresh'
    | '/api/libraries/$id'
    | '/api/webhooks/github'
    | '/dashboard/libraries/$id'
    | '/dashboard/libraries/add'
    | '/api/libraries'
    | '/dashboard/admin'
    | '/dashboard/libraries'
    | '/api/admin/discovery/queue'
    | '/api/admin/discovery/run'
    | '/api/admin/discovery/sources'
    | '/api/admin/users/$id'
    | '/api/github/verify/callback'
    | '/api/libraries/$id/docs'
    | '/api/libraries/$id/repo'
    | '/dashboard/admin/users/$id'
    | '/api/admin/discovery/sources/$id'
    | '/api/admin/libraries/$id/category'
    | '/api/admin/libraries/$id/rebuild'
    | '/api/admin/users/$id/flags'
    | '/api/libraries/$id/docs/build'
    | '/api/libraries/$id/repo/ingest'
    | '/api/libraries/$id/repo/verify'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/device'
    | '/docs'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/chat'
    | '/api/context'
    | '/api/crawl'
    | '/api/device-token'
    | '/api/embed'
    | '/api/ingest'
    | '/api/ingest-url'
    | '/api/keys'
    | '/api/mcp'
    | '/api/search'
    | '/dashboard/chat'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/admin/libraries'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/cron/discovery'
    | '/api/cron/refresh'
    | '/api/libraries/$id'
    | '/api/webhooks/github'
    | '/dashboard/libraries/$id'
    | '/dashboard/libraries/add'
    | '/api/libraries/'
    | '/dashboard/admin/'
    | '/dashboard/libraries/'
    | '/api/admin/discovery/queue'
    | '/api/admin/discovery/run'
    | '/api/admin/discovery/sources'
    | '/api/admin/users/$id'
    | '/api/github/verify/callback'
    | '/api/libraries/$id/docs'
    | '/api/libraries/$id/repo'
    | '/dashboard/admin/users/$id'
    | '/api/admin/discovery/sources/$id'
    | '/api/admin/libraries/$id/category'
    | '/api/admin/libraries/$id/rebuild'
    | '/api/admin/users/$id/flags'
    | '/api/libraries/$id/docs/build'
    | '/api/libraries/$id/repo/ingest'
    | '/api/libraries/$id/repo/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContextRoute: typeof ApiContextRoute
  ApiCrawlRoute: typeof ApiCrawlRoute
  ApiDeviceTokenRoute: typeof ApiDeviceTokenRoute
  ApiEmbedRoute: typeof ApiEmbedRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiIngestUrlRoute: typeof ApiIngestUrlRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAdminLibrariesRoute: typeof ApiAdminLibrariesRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDiscoveryRoute: typeof ApiCronDiscoveryRoute
  ApiCronRefreshRoute: typeof ApiCronRefreshRoute
  ApiLibrariesIdRoute: typeof ApiLibrariesIdRouteWithChildren
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiLibrariesIndexRoute: typeof ApiLibrariesIndexRoute
  ApiAdminDiscoveryQueueRoute: typeof ApiAdminDiscoveryQueueRoute
  ApiAdminDiscoveryRunRoute: typeof ApiAdminDiscoveryRunRoute
  ApiAdminDiscoverySourcesRoute: typeof ApiAdminDiscoverySourcesRouteWithChildren
  ApiGithubVerifyCallbackRoute: typeof ApiGithubVerifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-url': {
      id: '/api/ingest-url'
      path: '/api/ingest-url'
      fullPath: '/api/ingest-url'
      preLoaderRoute: typeof ApiIngestUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed': {
      id: '/api/embed'
      path: '/api/embed'
      fullPath: '/api/embed'
      preLoaderRoute: typeof ApiEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device-token': {
      id: '/api/device-token'
      path: '/api/device-token'
      fullPath: '/api/device-token'
      preLoaderRoute: typeof ApiDeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl': {
      id: '/api/crawl'
      path: '/api/crawl'
      fullPath: '/api/crawl'
      preLoaderRoute: typeof ApiCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context': {
      id: '/api/context'
      path: '/api/context'
      fullPath: '/api/context'
      preLoaderRoute: typeof ApiContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/libraries/': {
      id: '/dashboard/libraries/'
      path: '/libraries'
      fullPath: '/dashboard/libraries/'
      preLoaderRoute: typeof DashboardLibrariesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/libraries/': {
      id: '/api/libraries/'
      path: '/api/libraries'
      fullPath: '/api/libraries/'
      preLoaderRoute: typeof ApiLibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/libraries/add': {
      id: '/dashboard/libraries/add'
      path: '/libraries/add'
      fullPath: '/dashboard/libraries/add'
      preLoaderRoute: typeof DashboardLibrariesAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/libraries/$id': {
      id: '/dashboard/libraries/$id'
      path: '/libraries/$id'
      fullPath: '/dashboard/libraries/$id'
      preLoaderRoute: typeof DashboardLibrariesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/libraries/$id': {
      id: '/api/libraries/$id'
      path: '/api/libraries/$id'
      fullPath: '/api/libraries/$id'
      preLoaderRoute: typeof ApiLibrariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh': {
      id: '/api/cron/refresh'
      path: '/api/cron/refresh'
      fullPath: '/api/cron/refresh'
      preLoaderRoute: typeof ApiCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/discovery': {
      id: '/api/cron/discovery'
      path: '/api/cron/discovery'
      fullPath: '/api/cron/discovery'
      preLoaderRoute: typeof ApiCronDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/libraries': {
      id: '/api/admin/libraries'
      path: '/api/admin/libraries'
      fullPath: '/api/admin/libraries'
      preLoaderRoute: typeof ApiAdminLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users/$id': {
      id: '/dashboard/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/dashboard/admin/users/$id'
      preLoaderRoute: typeof DashboardAdminUsersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/libraries/$id/repo': {
      id: '/api/libraries/$id/repo'
      path: '/repo'
      fullPath: '/api/libraries/$id/repo'
      preLoaderRoute: typeof ApiLibrariesIdRepoRouteImport
      parentRoute: typeof ApiLibrariesIdRoute
    }
    '/api/libraries/$id/docs': {
      id: '/api/libraries/$id/docs'
      path: '/docs'
      fullPath: '/api/libraries/$id/docs'
      preLoaderRoute: typeof ApiLibrariesIdDocsRouteImport
      parentRoute: typeof ApiLibrariesIdRoute
    }
    '/api/github/verify/callback': {
      id: '/api/github/verify/callback'
      path: '/api/github/verify/callback'
      fullPath: '/api/github/verify/callback'
      preLoaderRoute: typeof ApiGithubVerifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/discovery/sources': {
      id: '/api/admin/discovery/sources'
      path: '/api/admin/discovery/sources'
      fullPath: '/api/admin/discovery/sources'
      preLoaderRoute: typeof ApiAdminDiscoverySourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/discovery/run': {
      id: '/api/admin/discovery/run'
      path: '/api/admin/discovery/run'
      fullPath: '/api/admin/discovery/run'
      preLoaderRoute: typeof ApiAdminDiscoveryRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/discovery/queue': {
      id: '/api/admin/discovery/queue'
      path: '/api/admin/discovery/queue'
      fullPath: '/api/admin/discovery/queue'
      preLoaderRoute: typeof ApiAdminDiscoveryQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/libraries/$id/repo/verify': {
      id: '/api/libraries/$id/repo/verify'
      path: '/verify'
      fullPath: '/api/libraries/$id/repo/verify'
      preLoaderRoute: typeof ApiLibrariesIdRepoVerifyRouteImport
      parentRoute: typeof ApiLibrariesIdRepoRoute
    }
    '/api/libraries/$id/repo/ingest': {
      id: '/api/libraries/$id/repo/ingest'
      path: '/ingest'
      fullPath: '/api/libraries/$id/repo/ingest'
      preLoaderRoute: typeof ApiLibrariesIdRepoIngestRouteImport
      parentRoute: typeof ApiLibrariesIdRepoRoute
    }
    '/api/libraries/$id/docs/build': {
      id: '/api/libraries/$id/docs/build'
      path: '/build'
      fullPath: '/api/libraries/$id/docs/build'
      preLoaderRoute: typeof ApiLibrariesIdDocsBuildRouteImport
      parentRoute: typeof ApiLibrariesIdDocsRoute
    }
    '/api/admin/users/$id/flags': {
      id: '/api/admin/users/$id/flags'
      path: '/flags'
      fullPath: '/api/admin/users/$id/flags'
      preLoaderRoute: typeof ApiAdminUsersIdFlagsRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/libraries/$id/rebuild': {
      id: '/api/admin/libraries/$id/rebuild'
      path: '/$id/rebuild'
      fullPath: '/api/admin/libraries/$id/rebuild'
      preLoaderRoute: typeof ApiAdminLibrariesIdRebuildRouteImport
      parentRoute: typeof ApiAdminLibrariesRoute
    }
    '/api/admin/libraries/$id/category': {
      id: '/api/admin/libraries/$id/category'
      path: '/$id/category'
      fullPath: '/api/admin/libraries/$id/category'
      preLoaderRoute: typeof ApiAdminLibrariesIdCategoryRouteImport
      parentRoute: typeof ApiAdminLibrariesRoute
    }
    '/api/admin/discovery/sources/$id': {
      id: '/api/admin/discovery/sources/$id'
      path: '/$id'
      fullPath: '/api/admin/discovery/sources/$id'
      preLoaderRoute: typeof ApiAdminDiscoverySourcesIdRouteImport
      parentRoute: typeof ApiAdminDiscoverySourcesRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLibrariesIdRoute: typeof DashboardLibrariesIdRoute
  DashboardLibrariesAddRoute: typeof DashboardLibrariesAddRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardLibrariesIndexRoute: typeof DashboardLibrariesIndexRoute
  DashboardAdminUsersIdRoute: typeof DashboardAdminUsersIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLibrariesIdRoute: DashboardLibrariesIdRoute,
  DashboardLibrariesAddRoute: DashboardLibrariesAddRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardLibrariesIndexRoute: DashboardLibrariesIndexRoute,
  DashboardAdminUsersIdRoute: DashboardAdminUsersIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiAdminLibrariesRouteChildren {
  ApiAdminLibrariesIdCategoryRoute: typeof ApiAdminLibrariesIdCategoryRoute
  ApiAdminLibrariesIdRebuildRoute: typeof ApiAdminLibrariesIdRebuildRoute
}

const ApiAdminLibrariesRouteChildren: ApiAdminLibrariesRouteChildren = {
  ApiAdminLibrariesIdCategoryRoute: ApiAdminLibrariesIdCategoryRoute,
  ApiAdminLibrariesIdRebuildRoute: ApiAdminLibrariesIdRebuildRoute,
}

const ApiAdminLibrariesRouteWithChildren =
  ApiAdminLibrariesRoute._addFileChildren(ApiAdminLibrariesRouteChildren)

interface ApiAdminUsersIdRouteChildren {
  ApiAdminUsersIdFlagsRoute: typeof ApiAdminUsersIdFlagsRoute
}

const ApiAdminUsersIdRouteChildren: ApiAdminUsersIdRouteChildren = {
  ApiAdminUsersIdFlagsRoute: ApiAdminUsersIdFlagsRoute,
}

const ApiAdminUsersIdRouteWithChildren = ApiAdminUsersIdRoute._addFileChildren(
  ApiAdminUsersIdRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRouteWithChildren
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRouteWithChildren,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiLibrariesIdDocsRouteChildren {
  ApiLibrariesIdDocsBuildRoute: typeof ApiLibrariesIdDocsBuildRoute
}

const ApiLibrariesIdDocsRouteChildren: ApiLibrariesIdDocsRouteChildren = {
  ApiLibrariesIdDocsBuildRoute: ApiLibrariesIdDocsBuildRoute,
}

const ApiLibrariesIdDocsRouteWithChildren =
  ApiLibrariesIdDocsRoute._addFileChildren(ApiLibrariesIdDocsRouteChildren)

interface ApiLibrariesIdRepoRouteChildren {
  ApiLibrariesIdRepoIngestRoute: typeof ApiLibrariesIdRepoIngestRoute
  ApiLibrariesIdRepoVerifyRoute: typeof ApiLibrariesIdRepoVerifyRoute
}

const ApiLibrariesIdRepoRouteChildren: ApiLibrariesIdRepoRouteChildren = {
  ApiLibrariesIdRepoIngestRoute: ApiLibrariesIdRepoIngestRoute,
  ApiLibrariesIdRepoVerifyRoute: ApiLibrariesIdRepoVerifyRoute,
}

const ApiLibrariesIdRepoRouteWithChildren =
  ApiLibrariesIdRepoRoute._addFileChildren(ApiLibrariesIdRepoRouteChildren)

interface ApiLibrariesIdRouteChildren {
  ApiLibrariesIdDocsRoute: typeof ApiLibrariesIdDocsRouteWithChildren
  ApiLibrariesIdRepoRoute: typeof ApiLibrariesIdRepoRouteWithChildren
}

const ApiLibrariesIdRouteChildren: ApiLibrariesIdRouteChildren = {
  ApiLibrariesIdDocsRoute: ApiLibrariesIdDocsRouteWithChildren,
  ApiLibrariesIdRepoRoute: ApiLibrariesIdRepoRouteWithChildren,
}

const ApiLibrariesIdRouteWithChildren = ApiLibrariesIdRoute._addFileChildren(
  ApiLibrariesIdRouteChildren,
)

interface ApiAdminDiscoverySourcesRouteChildren {
  ApiAdminDiscoverySourcesIdRoute: typeof ApiAdminDiscoverySourcesIdRoute
}

const ApiAdminDiscoverySourcesRouteChildren: ApiAdminDiscoverySourcesRouteChildren =
  {
    ApiAdminDiscoverySourcesIdRoute: ApiAdminDiscoverySourcesIdRoute,
  }

const ApiAdminDiscoverySourcesRouteWithChildren =
  ApiAdminDiscoverySourcesRoute._addFileChildren(
    ApiAdminDiscoverySourcesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeviceRoute: DeviceRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContextRoute: ApiContextRoute,
  ApiCrawlRoute: ApiCrawlRoute,
  ApiDeviceTokenRoute: ApiDeviceTokenRoute,
  ApiEmbedRoute: ApiEmbedRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiIngestUrlRoute: ApiIngestUrlRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAdminLibrariesRoute: ApiAdminLibrariesRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDiscoveryRoute: ApiCronDiscoveryRoute,
  ApiCronRefreshRoute: ApiCronRefreshRoute,
  ApiLibrariesIdRoute: ApiLibrariesIdRouteWithChildren,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiLibrariesIndexRoute: ApiLibrariesIndexRoute,
  ApiAdminDiscoveryQueueRoute: ApiAdminDiscoveryQueueRoute,
  ApiAdminDiscoveryRunRoute: ApiAdminDiscoveryRunRoute,
  ApiAdminDiscoverySourcesRoute: ApiAdminDiscoverySourcesRouteWithChildren,
  ApiGithubVerifyCallbackRoute: ApiGithubVerifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
